# Define a configuração padrão dos serviços e suas dependências.
version: '2'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
  discovery:
    container_name: discovery
    image: supremotribunalfederal/stfdigital-plataforma-discovery
  gateway:
    container_name: gateway
    image: supremotribunalfederal/stfdigital-plataforma-gateway
    depends_on:
     - discovery
  services:
    container_name: services
    image: supremotribunalfederal/stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
  mongo:
    container_name: mongo
    image: mongo:3
  documents:
    container_name: documents
    image: supremotribunalfederal/stfdigital-plataforma-documents
    depends_on:
     - mongo
     - discovery
     - onlyoffice
  ui:
    container_name: ui
    image: supremotribunalfederal/stfdigital-plataforma-ui
    depends_on:
     - gateway
  userauthentication:
    container_name: userauthentication
    image: supremotribunalfederal/stfdigital-plataforma-userauthentication
    depends_on:
     - discovery
  onlyoffice:
    container_name: onlyoffice