# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  discovery: # Ambassador apontando para o discovery rodando localmente
    container_name: discovery
    image: svendowideit/ambassador
    environment:
     - DISCOVERY_PORT_8761_TCP=tcp://${AMBASSADOR_HOST}:8761