# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  docker:
    environment:
     - ONLYOFFICE_PORT_443_TCP=tcp://onlyoffice:443
    depends_on:
     - onlyoffice
  onlyoffice:
    extends:
      file: shared/compose/common.yml
      service: onlyoffice
  recebimento:
    extends:
      file: shared/compose/common.yml
      service: recebimento
    image: stfdigital-autuacao-recebimento
    depends_on:
     - rabbit
     - discovery